name: 'dbt_llyod_cloud'
version: '1.0.0'


profile: 'dbt_llyod_cloud'

models:
  dbt_llyod_cloud:
    +schema: 

    # Bronze Stage Configuration
    bronze:
      +materialized: table

    # Silver Stage Configuration
    silver:
      +materialized: table

    # Gold Stage Configuration
    gold:
      +materialized: table
